import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

export function WhyFilm() { return <section className="why-film" aria-label="Vì sao chụp film"><div className="why-film-sticky"><div className="why-image"><Image src="/images/film/frame-07.webp" alt="Ảnh film: những lớp núi xanh dưới bầu trời rộng" fill sizes="100vw" quality={80} /></div><div className="why-shade" /><div className="why-inner"><span className="eyebrow">01 / VÌ SAO LÀ FILM</span><div className="why-lines"><p data-reveal><span>01 /</span>36 tấm ảnh.</p><p data-reveal><span>02 /</span>Không xem trước.</p><p data-reveal><span>03 /</span>Không chụp lại mãi.</p><p className="why-emphasis" data-reveal><span>04 /</span>Chỉ giữ điều bạn muốn nhớ.</p></div><span className="image-disclaimer">FILM PHOTOGRAPHY / SOORAH COLLECTION</span></div></div></section>; }

export function WhyThisFilm() { const cards = [{ no: "01", title: "Hằng ngày", copy: "Một buổi đi học, một góc phố, một chuyến đi ngắn. Bắt đầu từ những thứ ở ngay trước mắt." }, { no: "02", title: "Linh hoạt", copy: "ISO 400 cho bạn thêm khoảng thở khi ánh sáng thay đổi trong ngày." }, { no: "03", title: "Dễ bắt đầu", copy: "Không cần một dự án lớn. Một chiếc máy 35mm và một chút tò mò là đủ." }, { no: "04", title: "36 lần bấm máy", copy: "Nhiều hơn 24 khung hình. Vừa đủ để bạn thử, sai, rồi tìm ra điều mình thích." }]; return <section className="why-this section-pad"><div className="section-index"><span>02 / CHI TIẾT</span><span>CHO NHỮNG NGÀY BÌNH THƯỜNG</span></div><div className="why-this-heading"><h2 data-reveal>Dành cho<br /><em>ngày bình thường.</em></h2><p data-reveal>Không phải mọi khoảnh khắc đều cần trở thành một dịp đặc biệt để đáng chụp.</p></div><div className="reason-grid">{cards.map((card) => <article className="reason-card" key={card.no} data-reveal><span>{card.no} / 04</span><div><h3>{card.title}</h3><p>{card.copy}</p></div><span className="reason-arrow">↗</span></article>)}</div></section>; }

export function HowItWorks() { const steps = [{ title: "Chọn", copy: "Chọn một cuộn phù hợp với máy 35mm của bạn." }, { title: "Đặt", copy: "Gửi nội dung đơn; SOORAH xác nhận hàng và phí giao hàng." }, { title: "Chụp", copy: "Mang máy theo. Chụp điều khiến bạn dừng lại." }, { title: "Tráng", copy: "Tua film về và đưa đến tiệm để tráng, quét ảnh." }, { title: "Chia sẻ", copy: "Giữ cho riêng mình hoặc kể lại bằng những tấm hình." }]; return <section className="how-section section-pad"><div className="section-index"><span>03 / HÀNH TRÌNH</span><span>TỪ CÚ NHẤP ĐẾN TẤM ẢNH ĐẦU</span></div><h2 data-reveal>Mỗi cuộn film<br /><em>có nhịp riêng.</em></h2><div className="steps">{steps.map((step, index) => <div className="step" key={step.title} data-reveal><span className="step-no">0{index + 1}</span><h3>{step.title}</h3><p>{step.copy}</p><span className="step-line" /></div>)}</div></section>; }

export function FinalCTA() { return <section className="final-cta"><span className="eyebrow">MỘT CUỘN LÀ MỘT KHỞI ĐẦU</span><h2 data-reveal>Bắt đầu<br /><em>từ một cuộn.</em></h2><p>Không cần biết trước bức ảnh sẽ ra sao.</p><Link href="/product/kodak-ultramax-400" className="button button-light">MUA ULTRAMAX 400 <ArrowUpRight size={18} /></Link><span className="final-mark">SOORAH / 36 KHUNG HÌNH</span></section>; }
