import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import CheatSheet from "@/components/home/CheatSheet";
import { HowItWorks } from "@/components/home/StorySections";

export const metadata: Metadata = { title: "Cuộn film đầu tiên — Hướng dẫn", description: "Hướng dẫn dễ hiểu để chụp cuộn film 35mm đầu tiên, từ chọn film đến tráng và quét ảnh." };
export default function GuidePage() { return <><section className="guide-hero"><div className="editorial-hero-photo" aria-hidden="true"><Image src="/images/film/frame-14.webp" alt="" fill priority sizes="100vw" quality={82} /></div><div className="editorial-hero-shade" aria-hidden="true" /><span className="eyebrow">GHI CHÚ SOORAH / 001</span><h1>Cuộn film đầu<br /><em>không cần quá khó.</em></h1><p>Chỉ vài điều cần biết để bạn chụp cuộn 35mm đầu tiên tự tin hơn.</p><span className="guide-count">01 — 05 / BẮT ĐẦU NHANH</span></section><section className="guide-content section-pad"><div className="section-index"><span>ĐIỀU CẦN BIẾT</span><span>ĐỌC TRONG NĂM PHÚT</span></div><div className="guide-list"><article><span>01 /</span><div><h2>Kiểm tra máy.</h2><p>Máy của bạn cần dùng film 35mm. Nếu chưa chắc, kiểm tra tên máy hoặc hướng dẫn trước khi mua. Film 35mm không dùng được cho mọi loại máy.</p></div></article><article><span>02 /</span><div><h2>Lắp film trong bóng râm.</h2><p>Lắp film theo hướng dẫn của máy, tránh nắng gắt chiếu trực tiếp vào cuộn. Đảm bảo film được kéo đúng và bộ đếm khung hình bắt đầu chạy.</p></div></article><article><span>03 /</span><div><h2>Tìm ánh sáng.</h2><p>Ultramax 400 linh hoạt vào ban ngày. Khi trời tối hoặc trong nhà thiếu sáng, ảnh dễ bị thiếu sáng; cân nhắc dùng đèn chớp nếu máy có.</p></div></article><article><span>04 /</span><div><h2>Tua về trước khi mở máy.</h2><p>Chụp hết 36 tấm ảnh, tua film về hết hộp rồi mới mở nắp máy. Mở sớm sẽ làm lộ sáng phần film chưa được bảo vệ.</p></div></article><article><span>05 /</span><div><h2>Tráng, quét, giữ lại.</h2><p>Mang cuộn đến tiệm tráng film màu C-41. Bạn có thể chọn quét ảnh để nhận tệp số. Chi phí dịch vụ và vận chuyển không nằm trong giá film.</p></div></article></div></section><CheatSheet compact /><HowItWorks /><section className="guide-last"><span className="eyebrow">SẴN SÀNG KHI BẠN SẴN SÀNG</span><h2>Giờ thì xem<br /><em>điều gì xảy ra.</em></h2><Link href="/product/kodak-ultramax-400" className="button button-light">MUA ULTRAMAX 400 <ArrowUpRight size={17} /></Link></section></>; }
